SET SEARCH_PATH = seminar;

insert into instrument (brand, instrument_type, instrument_code, rental_fee) values ( 'Gretsch', 'violin', '4iPOZdp1XL', 41.94);
insert into instrument (brand, instrument_type, instrument_code, rental_fee) values ( 'Fender', 'piano', '3yvS5Vzgil', 82.77);
insert into instrument (brand, instrument_type, instrument_code, rental_fee) values ( 'Martin', 'piano', 'dmfzrnIALU', 84.86);
insert into instrument (brand, instrument_type, instrument_code, rental_fee) values ( 'Schecter', 'violin', 'lka8Vhv9ZL', 80.96);
insert into instrument (brand, instrument_type, instrument_code, rental_fee) values ( 'Yamaha', 'violin', 'nWtmTaiOqe', 117.92);
insert into instrument (brand, instrument_type, instrument_code, rental_fee) values ( 'PRS', 'cello', 'JCyKDGLDMX', 51.02);
insert into instrument (brand, instrument_type, instrument_code, rental_fee) values ( 'Gretsch', 'flute', 'SX7KfeoOuw', 109.64);
insert into instrument (brand, instrument_type, instrument_code, rental_fee) values ( 'Epiphone', 'saxophone', 'H5Grpyoy5q', 106.9);
insert into instrument (brand, instrument_type, instrument_code, rental_fee) values ( 'Schecter', 'drums', 'sexRuNjp6C', 88.95);
insert into instrument (brand, instrument_type, instrument_code, rental_fee) values ( 'Martin', 'trumpet', 'cAeIClGiOg', 43.83);
insert into instrument (brand, instrument_type, instrument_code, rental_fee) values ( 'Yamaha', 'guitar', 'iIJr9LwEJt', 54.88);
insert into instrument (brand, instrument_type, instrument_code, rental_fee) values ( 'Epiphone', 'violin', 'fwkzfovQds', 76.39);
insert into instrument (brand, instrument_type, instrument_code, rental_fee) values ( 'Martin', 'ukulele', 'MbQvQGKXc3', 84.31);
insert into instrument (brand, instrument_type, instrument_code, rental_fee) values ( 'Schecter', 'cello', '1OZD9c7Tg9', 99.34);
insert into instrument (brand, instrument_type, instrument_code, rental_fee) values ( 'Taylor', 'cello', 'zfkdLBPY19', 98.26);
insert into instrument (brand, instrument_type, instrument_code, rental_fee) values ( 'Ibanez', 'trumpet', 'oaZNZWemvx', 32.15);
insert into instrument (brand, instrument_type, instrument_code, rental_fee) values ( 'Epiphone', 'violin', '5A0fQrebqo', 116.67);
insert into instrument (brand, instrument_type, instrument_code, rental_fee) values ( 'Gretsch', 'piano', 'gLi3Sjlpvz', 86.46);
insert into instrument (brand, instrument_type, instrument_code, rental_fee) values ( 'Gibson', 'cello', 'EJJQahs9Sp', 59.54);
insert into instrument (brand, instrument_type, instrument_code, rental_fee) values ( 'PRS', 'bass guitar', 'Eh39aDzpST', 60.72);

insert into rental ( start_date, end_date, instrument_id) values ( '2021-04-02', '2023-04-26', 8);
insert into rental ( start_date, end_date, instrument_id) values ( '2021-11-11', '2023-02-07', 14);
insert into rental ( start_date, end_date, instrument_id) values ( '2022-01-19', '2023-01-07', 3);
insert into rental ( start_date, end_date, instrument_id) values ( '2021-01-13', '2023-07-30', 6);
insert into rental ( start_date, end_date, instrument_id) values ( '2021-12-16', '2023-10-23', 6);
insert into rental ( start_date, end_date, instrument_id) values ( '2022-05-25', '2023-01-08', 18);
insert into rental ( start_date, end_date, instrument_id) values ( '2022-04-14', '2023-08-08', 8);
insert into rental ( start_date, end_date, instrument_id) values ( '2021-08-03', '2023-03-25', 20);
insert into rental ( start_date, end_date, instrument_id) values ('2021-02-06', '2023-01-21', 5);
insert into rental ( start_date, end_date, instrument_id) values ( '2021-10-29', '2023-03-03', 1);
insert into rental ( start_date, end_date, instrument_id) values ( '2022-02-07', null, 18);
insert into rental ( start_date, end_date, instrument_id) values ( '2022-07-18', '2023-07-10', 10);
insert into rental ( start_date, end_date, instrument_id) values ( '2021-01-31', '2023-08-15', 17);
insert into rental ( start_date, end_date, instrument_id) values ( '2021-11-17', '2023-03-23', 10);
insert into rental ( start_date, end_date, instrument_id) values ( '2021-07-30', null, 17);

insert into student (person_number, first_name, last_name, enrollment_date, zip, city, street_adress) values ('78836316-2460', 'Teressa', 'Fidelus', '2017/10/28', '46157', 'Bulgan', '34933 Monterey Plaza');
insert into student (person_number, first_name, last_name, enrollment_date, zip, city, street_adress) values ('65990487-5909', 'Curcio', 'Gounin', '2007/12/31', '58761', 'Carangola', '23 Rigney Place');
insert into student (person_number, first_name, last_name, enrollment_date, zip, city, street_adress) values ('72302543-1294', 'Winfield', 'Windaybank', '2021/06/21', '69154', 'Boyeros', '8576 Vidon Road');
insert into student (person_number, first_name, last_name, enrollment_date, zip, city, street_adress) values ('11993379-9942', 'Corella', 'Baumford', '2015/12/24', '11529', 'Badajoz', '0786 Gulseth Hill');
insert into student (person_number, first_name, last_name, enrollment_date, zip, city, street_adress) values ('99784815-6795', 'Corbin', 'Polly', '2005/12/23', '63188', 'Acacías', '55466 4th Drive');
insert into student (person_number, first_name, last_name, enrollment_date, zip, city, street_adress) values ('73085945-1683', 'Fredek', 'Maffy', '2007/02/03', '29620', 'Frederiksberg', '74 Pawling Avenue');
insert into student (person_number, first_name, last_name, enrollment_date, zip, city, street_adress) values ('26206394-6321', 'Hurlee', 'Hounsham', '2005/04/24', '05638', 'Latung', '80891 Anhalt Park');
insert into student (person_number, first_name, last_name, enrollment_date, zip, city, street_adress) values ('43040860-5972', 'Marc', 'Hartin', '2010/10/08', '95308', 'Bataiporã', '92 Pierstorff Plaza');
insert into student (person_number, first_name, last_name, enrollment_date, zip, city, street_adress) values ('02771476-6875', 'Whittaker', 'Fussen', '2020/02/17', '15015', 'Gozdowo', '9604 Maple Junction');
insert into student (person_number, first_name, last_name, enrollment_date, zip, city, street_adress) values ('21298215-3673', 'Yolane', 'Simmank', '2000/11/29', '22627', 'Kotlovka', '14 Lillian Pass');
insert into student (person_number, first_name, last_name, enrollment_date, zip, city, street_adress) values ('32746873-3527', 'Gayle', 'Mountjoy', '2016/02/28', '45714', 'Angers', '09 Sachs Lane');
insert into student (person_number, first_name, last_name, enrollment_date, zip, city, street_adress) values ('13666424-8416', 'Antonella', 'Vaszoly', '2021/08/05', '60313', 'Mohelno', '37 Cascade Hill');
insert into student (person_number, first_name, last_name, enrollment_date, zip, city, street_adress) values ('17817711-3347', 'Dud', 'Giovanardi', '2007/02/19', '99374', 'Jiangchuan', '3433 John Wall Drive');
insert into student (person_number, first_name, last_name, enrollment_date, zip, city, street_adress) values ('10233233-5060', 'Jenifer', 'Dearlove', '2009/07/10', '79829', 'Zhifang', '1524 Bunting Alley');
insert into student (person_number, first_name, last_name, enrollment_date, zip, city, street_adress) values ('01172686-0730', 'Margaretha', 'Tulleth', '2019/10/17', '49087', 'Padina', '118 Mendota Way');
insert into student (person_number, first_name, last_name, enrollment_date, zip, city, street_adress) values ('25333057-3822', 'Allis', 'Vermer', '2021/09/13', '55458', 'Shingū', '1 Transport Trail');
insert into student (person_number, first_name, last_name, enrollment_date, zip, city, street_adress) values ('75283233-9940', 'Ciro', 'Wealthall', '2007/08/13', '76358', 'Kolindrós', '7276 Lotheville Alley');
insert into student (person_number, first_name, last_name, enrollment_date, zip, city, street_adress) values ('28451621-4935', 'Freemon', 'Knowles', '2020/09/17', '38275', 'Cajabamba', '4 Longview Parkway');
insert into student (person_number, first_name, last_name, enrollment_date, zip, city, street_adress) values ('93788143-1267', 'Vergil', 'Straine', '2007/12/05', '44393', 'Dallas', '61 Warbler Plaza');
insert into student (person_number, first_name, last_name, enrollment_date, zip, city, street_adress) values ('75315355-3543', 'Stanly', 'Collopy', '2018/01/04', '67035', 'Wangping', '56 Hudson Alley');

insert into students_renting(rental_id,student_id) values(6,1);
insert into students_renting(rental_id,student_id) values(15,1);
insert into students_renting(rental_id,student_id) values(5,2);
insert into students_renting(rental_id,student_id) values(4,3);
insert into students_renting(rental_id,student_id) values(8,5);
insert into students_renting(rental_id,student_id) values(1,6);
insert into students_renting(rental_id,student_id) values(2,6);
insert into students_renting(rental_id,student_id) values(14,7);
insert into students_renting(rental_id,student_id) values(10,8);
insert into students_renting(rental_id,student_id) values(4,8);
insert into students_renting(rental_id,student_id) values(7,9);
insert into students_renting(rental_id,student_id) values(3,10);
insert into students_renting(rental_id,student_id) values(9,11);
insert into students_renting(rental_id,student_id) values(11,12);
insert into students_renting(rental_id,student_id) values(12,13);
insert into students_renting(rental_id,student_id) values(13,14);


insert into max_rental_per_student(max_rental,set_date) values(2,'1999-12-31');











insert into phone_number_student (student_id, phone_number) values (18, '+62 133 923 0337');
insert into phone_number_student (student_id, phone_number) values (18, '+62 845 434 4912');
insert into phone_number_student (student_id, phone_number) values (8, '+598 188 686 7723');
insert into phone_number_student (student_id, phone_number) values (6, '+351 522 779 9172');
insert into phone_number_student (student_id, phone_number) values (20, '+234 413 146 9212');
insert into phone_number_student (student_id, phone_number) values (18, '+1 360 476 4878');
insert into phone_number_student (student_id, phone_number) values (18, '+84 266 567 7836');
insert into phone_number_student (student_id, phone_number) values (9, '+62 794 140 4664');
insert into phone_number_student (student_id, phone_number) values (3, '+62 116 838 7606');
insert into phone_number_student (student_id, phone_number) values (7, '+48 920 411 3201');
insert into phone_number_student (student_id, phone_number) values (17, '+55 992 168 8132');
insert into phone_number_student (student_id, phone_number) values (1, '+86 536 857 3983');
insert into phone_number_student (student_id, phone_number) values (7, '+1 562 592 1770');
insert into phone_number_student (student_id, phone_number) values (18, '+48 324 788 4399');
insert into phone_number_student (student_id, phone_number) values (15, '+54 231 392 8783');
insert into phone_number_student (student_id, phone_number) values (9, '+86 498 127 6692');
insert into phone_number_student (student_id, phone_number) values (6, '+56 759 444 4144');
insert into phone_number_student (student_id, phone_number) values (10, '+62 662 515 4911');
insert into phone_number_student (student_id, phone_number) values (5, '+86 690 241 0791');
insert into phone_number_student (student_id, phone_number) values (3, '+92 291 804 7663');
insert into phone_number_student (student_id, phone_number) values (2, '+62 460 982 2581');
insert into phone_number_student (student_id, phone_number) values (18, '+7 938 224 8800');
insert into phone_number_student (student_id, phone_number) values (7, '+46 475 575 7059');
insert into phone_number_student (student_id, phone_number) values (4, '+1 754 677 5892');
insert into phone_number_student (student_id, phone_number) values (6, '+55 690 370 7229');

insert into mail_adress_student (student_id, mail_adress) values (10, 'ekerins0@hugedomains.com');
insert into mail_adress_student (student_id, mail_adress) values (4, 'mcossem1@forbes.com');
insert into mail_adress_student (student_id, mail_adress) values (6, 'adrury2@4shared.com');
insert into mail_adress_student (student_id, mail_adress) values (2, 'rfolliott3@nbcnews.com');
insert into mail_adress_student (student_id, mail_adress) values (18, 'tcalderon4@nydailynews.com');
insert into mail_adress_student (student_id, mail_adress) values (13, 'bworts5@yolasite.com');
insert into mail_adress_student (student_id, mail_adress) values (10, 'ntrayford6@epa.gov');
insert into mail_adress_student (student_id, mail_adress) values (2, 'bkellegher7@printfriendly.com');
insert into mail_adress_student (student_id, mail_adress) values (18, 'awhightman8@webnode.com');
insert into mail_adress_student (student_id, mail_adress) values (6, 'yrodenburg9@usgs.gov');
insert into mail_adress_student (student_id, mail_adress) values (16, 'gdowneya@economist.com');
insert into mail_adress_student (student_id, mail_adress) values (13, 'srothchildb@oakley.com');
insert into mail_adress_student (student_id, mail_adress) values (7, 'jgambiec@meetup.com');
insert into mail_adress_student (student_id, mail_adress) values (11, 'yslanyd@tmall.com');
insert into mail_adress_student (student_id, mail_adress) values (2, 'afleotee@posterous.com');
insert into mail_adress_student (student_id, mail_adress) values (2, 'mmcramseyf@yahoo.co.jp');
insert into mail_adress_student (student_id, mail_adress) values (20, 'hmurrthumg@shop-pro.jp');
insert into mail_adress_student (student_id, mail_adress) values (14, 'fgricksh@nymag.com');
insert into mail_adress_student (student_id, mail_adress) values (5, 'rdowearsi@un.org');
insert into mail_adress_student (student_id, mail_adress) values (5, 'cearleyj@ameblo.jp');
insert into mail_adress_student (student_id, mail_adress) values (19, 'amcnicklek@sitemeter.com');
insert into mail_adress_student (student_id, mail_adress) values (19, 'tbinfordl@webs.com');
insert into mail_adress_student (student_id, mail_adress) values (12, 'dboscottm@tamu.edu');
insert into mail_adress_student (student_id, mail_adress) values (7, 'cgreenrodn@wikimedia.org');
insert into mail_adress_student (student_id, mail_adress) values (2, 'amalcolmsono@dell.com');
insert into mail_adress_student (student_id, mail_adress) values (18, 'sbridsonp@latimes.com');
insert into mail_adress_student (student_id, mail_adress) values (12, 'bmcphateq@plala.or.jp');
insert into mail_adress_student (student_id, mail_adress) values (7, 'sbenckr@over-blog.com');
insert into mail_adress_student (student_id, mail_adress) values (20, 'granklins@dagondesign.com');
insert into mail_adress_student (student_id, mail_adress) values (3, 'gbradyt@edublogs.org');

insert into sibling_of_student (student_id, sibling_id) values (7, 19);
insert into sibling_of_student (student_id, sibling_id) values (7, 17);
insert into sibling_of_student (student_id, sibling_id) values (6, 19);
insert into sibling_of_student (student_id, sibling_id) values (2, 12);
insert into sibling_of_student (student_id, sibling_id) values (4, 17);
insert into sibling_of_student (student_id, sibling_id) values (9, 14);
insert into sibling_of_student (student_id, sibling_id) values (3, 14);
insert into sibling_of_student (student_id, sibling_id) values (7, 16);
insert into sibling_of_student (student_id, sibling_id) values (8, 15);
insert into sibling_of_student (student_id, sibling_id) values (5, 13);
insert into sibling_of_student (student_id, sibling_id) values (8, 17);
insert into sibling_of_student (student_id, sibling_id) values (9, 20);
insert into sibling_of_student (student_id, sibling_id) values (10, 19);
insert into sibling_of_student (student_id, sibling_id) values (4, 20);
insert into sibling_of_student (student_id, sibling_id) values (9, 19);
insert into sibling_of_student (student_id, sibling_id) values (1, 11);
insert into sibling_of_student (student_id, sibling_id) values (3, 13);
insert into sibling_of_student (student_id, sibling_id) values (1, 12);
insert into sibling_of_student (student_id, sibling_id) values (6, 13);
insert into sibling_of_student (student_id, sibling_id) values (10, 13);
insert into sibling_of_student (student_id, sibling_id) values (4, 16);
insert into sibling_of_student (student_id, sibling_id) values (3, 17);
insert into sibling_of_student (student_id, sibling_id) values (4, 13);
insert into sibling_of_student (student_id, sibling_id) values (8, 20);
insert into sibling_of_student (student_id, sibling_id) values (8, 19);
insert into sibling_of_student (student_id, sibling_id) values (6, 14);

insert into contact_person (person_number, first_name, last_name) values ( '68546531-3887', 'Washington', 'Harrinson');
insert into contact_person (person_number, first_name, last_name) values ('53863163-1314', 'Karlen', 'Warrior');
insert into contact_person (person_number, first_name, last_name) values ( '20294732-7996', 'Thedrick', 'Huett');
insert into contact_person (person_number, first_name, last_name) values ( '60896619-1580', 'Otis', 'Agg');
insert into contact_person (person_number, first_name, last_name) values ('37266745-7081', 'Arnoldo', 'Aliman');
insert into contact_person (person_number, first_name, last_name) values ('18725973-7628', 'Ebeneser', 'Ghio');
insert into contact_person (person_number, first_name, last_name) values ( '33572155-6133', 'Courtnay', 'Markussen');
insert into contact_person (person_number, first_name, last_name) values ('02063624-4637', 'Brandais', 'Adamowitz');
insert into contact_person (person_number, first_name, last_name) values ('94176550-3379', 'Meredith', 'Czaple');
insert into contact_person (person_number, first_name, last_name) values ('73502929-8874', 'Evey', 'Robjohns');
insert into contact_person (person_number, first_name, last_name) values ( '95141443-7518', 'Way', 'Bodycomb');
insert into contact_person (person_number, first_name, last_name) values ('55018831-4468', 'Eldon', 'Coling');
insert into contact_person (person_number, first_name, last_name) values ('51833916-8892', 'Karyn', 'Stump');
insert into contact_person (person_number, first_name, last_name) values ('63355337-2360', 'Atalanta', 'Bonnar');
insert into contact_person (person_number, first_name, last_name) values ( '01636448-9436', 'Doy', 'Lope');
insert into contact_person (person_number, first_name, last_name) values ( '51179063-1259', 'Jermayne', 'Eliet');
insert into contact_person (person_number, first_name, last_name) values ( '47224892-2609', 'Darb', 'Cranmere');
insert into contact_person (person_number, first_name, last_name) values ('60470077-7216', 'Putnam', 'Blei');
insert into contact_person (person_number, first_name, last_name) values ('78778243-6458', 'Angelle', 'Broad');
insert into contact_person (person_number, first_name, last_name) values ( '31315358-7172', 'Veradis', 'Monelli');

insert into contact_person_of_student (contact_person_id, student_id) values (3, 13);
insert into contact_person_of_student (contact_person_id, student_id) values (1, 4);
insert into contact_person_of_student (contact_person_id, student_id) values (12, 12);
insert into contact_person_of_student (contact_person_id, student_id) values (8, 1);
insert into contact_person_of_student (contact_person_id, student_id) values (8, 5);
insert into contact_person_of_student (contact_person_id, student_id) values (11, 8);
insert into contact_person_of_student (contact_person_id, student_id) values (7, 17);
insert into contact_person_of_student (contact_person_id, student_id) values (20, 9);
insert into contact_person_of_student (contact_person_id, student_id) values (11, 3);
insert into contact_person_of_student (contact_person_id, student_id) values (18, 14);
insert into contact_person_of_student (contact_person_id, student_id) values (12, 19);
insert into contact_person_of_student (contact_person_id, student_id) values (7, 18);
insert into contact_person_of_student (contact_person_id, student_id) values (16, 18);
insert into contact_person_of_student (contact_person_id, student_id) values (9, 14);
insert into contact_person_of_student (contact_person_id, student_id) values (2, 1);
insert into contact_person_of_student (contact_person_id, student_id) values (13, 19);
insert into contact_person_of_student (contact_person_id, student_id) values (15, 12);
insert into contact_person_of_student (contact_person_id, student_id) values (9, 1);
insert into contact_person_of_student (contact_person_id, student_id) values (7, 9);
insert into contact_person_of_student (contact_person_id, student_id) values (1, 5);


insert into phone_number_contact_person (contact_person_id, phone_number) values (1, '+48 740 160 8811');
insert into phone_number_contact_person (contact_person_id, phone_number) values (2, '+47 177 589 4143');
insert into phone_number_contact_person (contact_person_id, phone_number) values (3, '+84 726 584 5170');
insert into phone_number_contact_person (contact_person_id, phone_number) values (4, '+46 309 221 1127');
insert into phone_number_contact_person (contact_person_id, phone_number) values (5, '+86 533 705 5382');
insert into phone_number_contact_person (contact_person_id, phone_number) values (6, '+967 218 450 9372');
insert into phone_number_contact_person (contact_person_id, phone_number) values (7, '+351 907 142 9816');
insert into phone_number_contact_person (contact_person_id, phone_number) values (8, '+51 702 803 9076');
insert into phone_number_contact_person (contact_person_id, phone_number) values (9, '+62 554 641 7793');
insert into phone_number_contact_person (contact_person_id, phone_number) values (10, '+86 925 557 0031');
insert into phone_number_contact_person (contact_person_id, phone_number) values (11, '+41 927 793 0951');
insert into phone_number_contact_person (contact_person_id, phone_number) values (12, '+62 393 479 8832');
insert into phone_number_contact_person (contact_person_id, phone_number) values (13, '+98 938 490 3800');
insert into phone_number_contact_person (contact_person_id, phone_number) values (14, '+33 585 331 7131');
insert into phone_number_contact_person (contact_person_id, phone_number) values (15, '+55 206 623 6871');
insert into phone_number_contact_person (contact_person_id, phone_number) values (16, '+351 251 589 4794');
insert into phone_number_contact_person (contact_person_id, phone_number) values (17, '+7 635 226 6627');
insert into phone_number_contact_person (contact_person_id, phone_number) values (18, '+55 870 831 9290');
insert into phone_number_contact_person (contact_person_id, phone_number) values (19, '+55 549 131 9613');
insert into phone_number_contact_person (contact_person_id, phone_number) values (20, '+234 639 183 8656');

insert into mail_adress_contact_person (contact_person_id, mail_adress) values (1, 'tebbins0@nih.gov');
insert into mail_adress_contact_person (contact_person_id, mail_adress) values (2, 'dducker1@msu.edu');
insert into mail_adress_contact_person (contact_person_id, mail_adress) values (3, 'cmatous2@taobao.com');
insert into mail_adress_contact_person (contact_person_id, mail_adress) values (4, 'ogoodbairn3@blogs.com');
insert into mail_adress_contact_person (contact_person_id, mail_adress) values (5, 'dodea4@shinystat.com');
insert into mail_adress_contact_person (contact_person_id, mail_adress) values (6, 'edancey5@fda.gov');
insert into mail_adress_contact_person (contact_person_id, mail_adress) values (7, 'svokes6@weebly.com');
insert into mail_adress_contact_person (contact_person_id, mail_adress) values (8, 'lgarrelts7@dailymail.co.uk');
insert into mail_adress_contact_person (contact_person_id, mail_adress) values (9, 'wwitard8@wp.com');
insert into mail_adress_contact_person (contact_person_id, mail_adress) values (10, 'aygoe9@arstechnica.com');
insert into mail_adress_contact_person (contact_person_id, mail_adress) values (11, 'rmcgorleya@pen.io');
insert into mail_adress_contact_person (contact_person_id, mail_adress) values (12, 'bjanaszkiewiczb@ucoz.ru');
insert into mail_adress_contact_person (contact_person_id, mail_adress) values (13, 'vsliddersc@npr.org');
insert into mail_adress_contact_person (contact_person_id, mail_adress) values (14, 'bmetzigd@tiny.cc');
insert into mail_adress_contact_person (contact_person_id, mail_adress) values (15, 'etuleye@latimes.com');
insert into mail_adress_contact_person (contact_person_id, mail_adress) values (16, 'kgoginf@engadget.com');
insert into mail_adress_contact_person (contact_person_id, mail_adress) values (17, 'pcountg@whitehouse.gov');
insert into mail_adress_contact_person (contact_person_id, mail_adress) values (18, 'esummersetth@blogspot.com');
insert into mail_adress_contact_person (contact_person_id, mail_adress) values (19, 'aseebornei@gmpg.org');
insert into mail_adress_contact_person (contact_person_id, mail_adress) values (20, 'lenterleinj@vinaora.com');

insert into instructor (person_number, first_name, last_name) values ('09579382-5190', 'Terrel', 'Tattersdill');
insert into instructor (person_number, first_name, last_name) values ('68492350-4287', 'Norbert', 'Ringer');
insert into instructor (person_number, first_name, last_name) values ('94514133-7524', 'Sawyere', 'Duffield');
insert into instructor (person_number, first_name, last_name) values ('31454788-4606', 'Carey', 'Harsum');
insert into instructor (person_number, first_name, last_name) values ('85019316-3905', 'Cthrine', 'Bazely');
insert into instructor (person_number, first_name, last_name) values ('57533654-8563', 'Agretha', 'Baldinotti');
insert into instructor (person_number, first_name, last_name) values ('71128038-3698', 'Ola', 'Kohler');
insert into instructor (person_number, first_name, last_name) values ('75173948-4462', 'Talia', 'Rosingdall');
insert into instructor (person_number, first_name, last_name) values ('62560339-8575', 'Kaia', 'Vaughn');
insert into instructor (person_number, first_name, last_name) values ('82830781-4583', 'Mandi', 'Sharplin');

insert into phone_number_instructor (instructor_id, phone_number) values (2, '+86 971 134 9350');
insert into phone_number_instructor (instructor_id, phone_number) values (9, '+62 997 951 3490');
insert into phone_number_instructor (instructor_id, phone_number) values (10, '+86 183 914 9788');
insert into phone_number_instructor (instructor_id, phone_number) values (1, '+62 357 424 2706');
insert into phone_number_instructor (instructor_id, phone_number) values (3, '+1 608 531 1236');
insert into phone_number_instructor (instructor_id, phone_number) values (8, '+86 157 877 6910');
insert into phone_number_instructor (instructor_id, phone_number) values (10, '+351 187 622 8985');
insert into phone_number_instructor (instructor_id, phone_number) values (1, '+51 996 648 3030');
insert into phone_number_instructor (instructor_id, phone_number) values (3, '+84 280 885 8643');
insert into phone_number_instructor (instructor_id, phone_number) values (4, '+963 915 125 0594');
insert into phone_number_instructor (instructor_id, phone_number) values (3, '+55 161 883 9263');
insert into phone_number_instructor (instructor_id, phone_number) values (10, '+66 272 742 2576');
insert into phone_number_instructor (instructor_id, phone_number) values (7, '+86 173 908 4574');
insert into phone_number_instructor (instructor_id, phone_number) values (10, '+51 146 289 1167');
insert into phone_number_instructor (instructor_id, phone_number) values (9, '+62 985 485 2071');
insert into phone_number_instructor (instructor_id, phone_number) values (3, '+30 970 437 5162');
insert into phone_number_instructor (instructor_id, phone_number) values (6, '+49 788 605 7634');
insert into phone_number_instructor (instructor_id, phone_number) values (3, '+420 257 528 7348');
insert into phone_number_instructor (instructor_id, phone_number) values (7, '+503 748 495 2005');
insert into phone_number_instructor (instructor_id, phone_number) values (2, '+81 335 537 1150');
insert into phone_number_instructor (instructor_id, phone_number) values (4, '+238 469 140 0167');
insert into phone_number_instructor (instructor_id, phone_number) values (10, '+62 367 443 1088');
insert into phone_number_instructor (instructor_id, phone_number) values (1, '+63 390 576 6630');
insert into phone_number_instructor (instructor_id, phone_number) values (2, '+1 512 457 8327');
insert into phone_number_instructor (instructor_id, phone_number) values (4, '+62 365 512 3797');

insert into mail_adress_instructor (instructor_id, mail_adress) values (7, 'kschuler0@hostgator.com');
insert into mail_adress_instructor (instructor_id, mail_adress) values (8, 'dstanfield1@constantcontact.com');
insert into mail_adress_instructor (instructor_id, mail_adress) values (2, 'yrennison2@e-recht24.de');
insert into mail_adress_instructor (instructor_id, mail_adress) values (6, 'mgauge3@bigcartel.com');
insert into mail_adress_instructor (instructor_id, mail_adress) values (6, 'jsampey4@xinhuanet.com');
insert into mail_adress_instructor (instructor_id, mail_adress) values (2, 'fmyderscough5@jiathis.com');
insert into mail_adress_instructor (instructor_id, mail_adress) values (3, 'bdallas6@princeton.edu');
insert into mail_adress_instructor (instructor_id, mail_adress) values (6, 'knevill7@chron.com');
insert into mail_adress_instructor (instructor_id, mail_adress) values (7, 'mrosendale8@hhs.gov');
insert into mail_adress_instructor (instructor_id, mail_adress) values (9, 'aghost9@cnn.com');
insert into mail_adress_instructor (instructor_id, mail_adress) values (3, 'dshoobridgea@jiathis.com');
insert into mail_adress_instructor (instructor_id, mail_adress) values (1, 'amaccostyeb@blog.com');
insert into mail_adress_instructor (instructor_id, mail_adress) values (6, 'farnowc@arstechnica.com');
insert into mail_adress_instructor (instructor_id, mail_adress) values (10, 'gwellfared@reverbnation.com');
insert into mail_adress_instructor (instructor_id, mail_adress) values (6, 'lsiegertsze@lycos.com');
insert into mail_adress_instructor (instructor_id, mail_adress) values (6, 'awitulf@quantcast.com');
insert into mail_adress_instructor (instructor_id, mail_adress) values (4, 'fhawardg@guardian.co.uk');
insert into mail_adress_instructor (instructor_id, mail_adress) values (1, 'nscoyneh@netscape.com');
insert into mail_adress_instructor (instructor_id, mail_adress) values (4, 'jmosedilli@gizmodo.com');
insert into mail_adress_instructor (instructor_id, mail_adress) values (7, 'tsowtenj@mtv.com');
insert into mail_adress_instructor (instructor_id, mail_adress) values (9, 'noshevlink@abc.net.au');
insert into mail_adress_instructor (instructor_id, mail_adress) values (5, 'pbrashl@goo.gl');
insert into mail_adress_instructor (instructor_id, mail_adress) values (3, 'waudrittm@topsy.com');
insert into mail_adress_instructor (instructor_id, mail_adress) values (6, 'jdashkovichn@hugedomains.com');
insert into mail_adress_instructor (instructor_id, mail_adress) values (6, 'dlefrieco@ed.gov');
insert into mail_adress_instructor (instructor_id, mail_adress) values (3, 'mbrookesp@arizona.edu');
insert into mail_adress_instructor (instructor_id, mail_adress) values (4, 'cchezierq@jalbum.net');
insert into mail_adress_instructor (instructor_id, mail_adress) values (5, 'ablarer@msn.com');
insert into mail_adress_instructor (instructor_id, mail_adress) values (9, 'ecreaneys@psu.edu');
insert into mail_adress_instructor (instructor_id, mail_adress) values (8, 'wpautott@dedecms.com');

insert into discount (discount_percentage, discount_date, number_of_siblings_required) values (0.96, '2006-05-13', 1);
insert into discount (discount_percentage, discount_date, number_of_siblings_required) values (0.67, '2012-03-13', 1);
insert into discount (discount_percentage, discount_date, number_of_siblings_required) values (0.65, '2006-08-12', 1);
insert into discount (discount_percentage, discount_date, number_of_siblings_required) values (0.89, '2017-05-28', 1);
insert into discount (discount_percentage, discount_date, number_of_siblings_required) values (0.33, '2011-07-18', 1);
insert into discount (discount_percentage, discount_date, number_of_siblings_required) values (0.22, '2000-12-12', 1);
insert into discount (discount_percentage, discount_date, number_of_siblings_required) values (0.55, '2003-12-31', 1);
insert into discount (discount_percentage, discount_date, number_of_siblings_required) values (0.16, '2007-01-26', 1);
insert into discount (discount_percentage, discount_date, number_of_siblings_required) values (0.94, '2011-11-18', 1);
insert into discount (discount_percentage, discount_date, number_of_siblings_required) values (0.9, '2018-04-30', 1);

insert into avalible_time (instructor_id, time_start, time_end, avalible_date) values (1, '6:16', '16:29', '2023-10-25');
insert into avalible_time (instructor_id, time_start, time_end, avalible_date) values (8, '6:22', '21:20', '2023-09-28');
insert into avalible_time (instructor_id, time_start, time_end, avalible_date) values (6, '5:26', '18:45', '2020-12-21');
insert into avalible_time (instructor_id, time_start, time_end, avalible_date) values (1, '3:24', '19:07', '2020-12-19');
insert into avalible_time (instructor_id, time_start, time_end, avalible_date) values (8, '5:32', '18:41', '2022-02-25');
insert into avalible_time (instructor_id, time_start, time_end, avalible_date) values (8, '2:30', '13:06', '2020-06-03');
insert into avalible_time (instructor_id, time_start, time_end, avalible_date) values (7, '7:58', '23:30', '2022-10-06');
insert into avalible_time (instructor_id, time_start, time_end, avalible_date) values (1, '3:46', '17:21', '2020-06-24');
insert into avalible_time (instructor_id, time_start, time_end, avalible_date) values (6, '2:17', '21:04', '2020-11-23');
insert into avalible_time (instructor_id, time_start, time_end, avalible_date) values (7, '2:23', '21:25', '2020-01-14');
insert into avalible_time (instructor_id, time_start, time_end, avalible_date) values (10, '5:53', '14:58', '2022-04-14');
insert into avalible_time (instructor_id, time_start, time_end, avalible_date) values (7, '2:45', '17:53', '2023-07-31');
insert into avalible_time (instructor_id, time_start, time_end, avalible_date) values (5, '7:15', '20:27', '2022-04-24');
insert into avalible_time (instructor_id, time_start, time_end, avalible_date) values (4, '3:37', '13:42', '2021-08-14');
insert into avalible_time (instructor_id, time_start, time_end, avalible_date) values (3, '4:39', '13:21', '2020-11-02');
insert into avalible_time (instructor_id, time_start, time_end, avalible_date) values (4, '4:05', '13:29', '2021-10-12');
insert into avalible_time (instructor_id, time_start, time_end, avalible_date) values (3, '5:37', '16:51', '2022-10-17');
insert into avalible_time (instructor_id, time_start, time_end, avalible_date) values (1, '3:27', '18:51', '2022-11-23');
insert into avalible_time (instructor_id, time_start, time_end, avalible_date) values (6, '4:38', '20:25', '2021-01-10');
insert into avalible_time (instructor_id, time_start, time_end, avalible_date) values (3, '1:31', '21:48', '2023-09-03');
insert into avalible_time (instructor_id, time_start, time_end, avalible_date) values (5, '5:32', '21:17', '2022-12-12');
insert into avalible_time (instructor_id, time_start, time_end, avalible_date) values (1, '6:14', '15:19', '2023-09-29');
insert into avalible_time (instructor_id, time_start, time_end, avalible_date) values (8, '1:15', '17:12', '2020-02-23');
insert into avalible_time (instructor_id, time_start, time_end, avalible_date) values (5, '1:26', '22:43', '2023-02-27');
insert into avalible_time (instructor_id, time_start, time_end, avalible_date) values (8, '1:35', '14:12', '2022-01-25');
insert into avalible_time (instructor_id, time_start, time_end, avalible_date) values (4, '3:25', '16:09', '2020-03-14');
insert into avalible_time (instructor_id, time_start, time_end, avalible_date) values (5, '5:37', '13:31', '2020-01-22');
insert into avalible_time (instructor_id, time_start, time_end, avalible_date) values (8, '4:41', '17:12', '2021-03-13');
insert into avalible_time (instructor_id, time_start, time_end, avalible_date) values (6, '2:15', '16:31', '2022-02-01');
insert into avalible_time (instructor_id, time_start, time_end, avalible_date) values (7, '3:15', '21:43', '2022-04-01');
insert into avalible_time (instructor_id, time_start, time_end, avalible_date) values (10, '7:44', '18:52', '2020-12-22');
insert into avalible_time (instructor_id, time_start, time_end, avalible_date) values (5, '2:00', '14:11', '2023-10-14');
insert into avalible_time (instructor_id, time_start, time_end, avalible_date) values (6, '1:05', '18:43', '2021-01-14');
insert into avalible_time (instructor_id, time_start, time_end, avalible_date) values (3, '5:49', '14:58', '2023-11-05');
insert into avalible_time (instructor_id, time_start, time_end, avalible_date) values (6, '7:20', '19:24', '2023-01-09');
insert into avalible_time (instructor_id, time_start, time_end, avalible_date) values (4, '7:02', '18:05', '2020-10-26');
insert into avalible_time (instructor_id, time_start, time_end, avalible_date) values (4, '2:40', '14:20', '2020-11-28');
insert into avalible_time (instructor_id, time_start, time_end, avalible_date) values (6, '7:05', '13:32', '2021-07-30');
insert into avalible_time (instructor_id, time_start, time_end, avalible_date) values (1, '7:10', '21:58', '2020-08-02');
insert into avalible_time (instructor_id, time_start, time_end, avalible_date) values (8, '3:55', '21:48', '2021-02-27');

insert into cost_per_lesson (lesson_type, skill_level, price_set_date, price) values ('individual', 'advanced', '2021-03-03', 929);
insert into cost_per_lesson (lesson_type, skill_level, price_set_date, price) values ('group', 'intermediate', '2023-02-13', 639);
insert into cost_per_lesson (lesson_type, skill_level, price_set_date, price) values ('individual', 'intermediate', '2022-02-03', 623);
insert into cost_per_lesson (lesson_type, skill_level, price_set_date, price) values ('individual', 'intermediate', '2022-05-02', 640);
insert into cost_per_lesson (lesson_type, skill_level, price_set_date, price) values ('individual', 'advanced', '2023-02-21', 588);
insert into cost_per_lesson (lesson_type, skill_level, price_set_date, price) values ('group', 'beginner', '2022-06-25', 956);
insert into cost_per_lesson (lesson_type, skill_level, price_set_date, price) values ('ensamble', 'beginner', '2020-08-13', 937);
insert into cost_per_lesson (lesson_type, skill_level, price_set_date, price) values ('ensamble', 'advanced', '2020-10-21', 537);
insert into cost_per_lesson (lesson_type, skill_level, price_set_date, price) values ('individual', 'advanced', '2022-09-30', 899);
insert into cost_per_lesson (lesson_type, skill_level, price_set_date, price) values ('ensamble', 'beginner', '2022-07-25', 777);
insert into cost_per_lesson (lesson_type, skill_level, price_set_date, price) values ('individual', 'intermediate', '2021-08-20', 619);
insert into cost_per_lesson (lesson_type, skill_level, price_set_date, price) values ('individual', 'beginner', '2023-01-03', 894);
insert into cost_per_lesson (lesson_type, skill_level, price_set_date, price) values ('individual', 'beginner', '2021-07-11', 660);
insert into cost_per_lesson (lesson_type, skill_level, price_set_date, price) values ('individual', 'advanced', '2023-08-29', 676);
insert into cost_per_lesson (lesson_type, skill_level, price_set_date, price) values ('individual', 'advanced', '2020-12-04', 578);
insert into cost_per_lesson (lesson_type, skill_level, price_set_date, price) values ('group', 'intermediate', '2021-07-28', 964);
insert into cost_per_lesson (lesson_type, skill_level, price_set_date, price) values ('group', 'beginner', '2021-08-16', 900);
insert into cost_per_lesson (lesson_type, skill_level, price_set_date, price) values ('group', 'advanced', '2021-06-23', 994);
insert into cost_per_lesson (lesson_type, skill_level, price_set_date, price) values ('individual', 'advanced', '2020-03-03', 532);
insert into cost_per_lesson (lesson_type, skill_level, price_set_date, price) values ('ensamble', 'intermediate', '2022-07-28', 999);
insert into cost_per_lesson (lesson_type, skill_level, price_set_date, price) values ('individual', 'intermediate', '2020-05-29', 623);
insert into cost_per_lesson (lesson_type, skill_level, price_set_date, price) values ('individual', 'intermediate', '2021-07-29', 526);
insert into cost_per_lesson (lesson_type, skill_level, price_set_date, price) values ('individual', 'intermediate', '2021-01-08', 532);
insert into cost_per_lesson (lesson_type, skill_level, price_set_date, price) values ('individual', 'advanced', '2021-10-27', 764);
insert into cost_per_lesson (lesson_type, skill_level, price_set_date, price) values ('individual', 'beginner', '2020-08-12', 656);
insert into cost_per_lesson (lesson_type, skill_level, price_set_date, price) values ('individual', 'advanced', '2021-11-18', 843);
insert into cost_per_lesson (lesson_type, skill_level, price_set_date, price) values ('group', 'advanced', '2022-08-09', 827);
insert into cost_per_lesson (lesson_type, skill_level, price_set_date, price) values ('individual', 'beginner', '2023-02-01', 555);
insert into cost_per_lesson (lesson_type, skill_level, price_set_date, price) values ('ensamble', 'beginner', '2022-02-11', 643);
insert into cost_per_lesson (lesson_type, skill_level, price_set_date, price) values ('group', 'intermediate', '2023-02-01', 829);

insert into individual_lesson (lesson_description, instrument_type, lesson_type, skill_level, price_set_date) values ('vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere', 'ukulele', 'individual', 'beginner', '2020-08-12');
insert into individual_lesson (lesson_description, instrument_type, lesson_type, skill_level, price_set_date) values ('eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla', 'guitar', 'individual', 'intermediate', '2022-05-02');
insert into individual_lesson (lesson_description, instrument_type, lesson_type, skill_level, price_set_date) values ('aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan', 'cello', 'individual', 'advanced', '2023-02-21');
insert into individual_lesson (lesson_description, instrument_type, lesson_type, skill_level, price_set_date) values ('justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id', 'bass guitar', 'individual', 'intermediate', '2021-08-20');
insert into individual_lesson (lesson_description, instrument_type, lesson_type, skill_level, price_set_date) values ('massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum', 'saxophone', 'individual', 'advanced', '2022-09-30');
insert into individual_lesson (lesson_description, instrument_type, lesson_type, skill_level, price_set_date) values ('quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec', 'ukulele', 'individual', 'beginner', '2020-08-12');
insert into individual_lesson (lesson_description, instrument_type, lesson_type, skill_level, price_set_date) values ('odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc', 'guitar', 'individual', 'advanced', '2022-09-30');
insert into individual_lesson (lesson_description, instrument_type, lesson_type, skill_level, price_set_date) values ('mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis', 'violin', 'individual', 'advanced', '2020-03-03');
insert into individual_lesson (lesson_description, instrument_type, lesson_type, skill_level, price_set_date) values ('posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac', 'drums', 'individual', 'advanced', '2020-03-03');
insert into individual_lesson (lesson_description, instrument_type, lesson_type, skill_level, price_set_date) values ('risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis', 'drums', 'individual', 'beginner', '2021-07-11');
insert into individual_lesson (lesson_description, instrument_type, lesson_type, skill_level, price_set_date) values ('fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer', 'cello', 'individual', 'advanced', '2020-03-03');
insert into individual_lesson (lesson_description, instrument_type, lesson_type, skill_level, price_set_date) values ('erat tortor sollicitudin mi sit amet lobortis sapien sapien non', 'bass guitar', 'individual', 'intermediate', '2022-05-02');
insert into individual_lesson (lesson_description, instrument_type, lesson_type, skill_level, price_set_date) values ('sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis', 'drums', 'individual', 'advanced', '2021-11-18');
insert into individual_lesson (lesson_description, instrument_type, lesson_type, skill_level, price_set_date) values ('suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat', 'cello', 'individual', 'beginner', '2020-08-12');
insert into individual_lesson (lesson_description, instrument_type, lesson_type, skill_level, price_set_date) values ('montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id', 'drums', 'individual', 'advanced', '2023-08-29');
insert into individual_lesson (lesson_description, instrument_type, lesson_type, skill_level, price_set_date) values ('erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat', 'saxophone', 'individual', 'intermediate', '2022-05-02');
insert into individual_lesson (lesson_description, instrument_type, lesson_type, skill_level, price_set_date) values ('magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis', 'violin', 'individual', 'beginner', '2021-07-11');
insert into individual_lesson (lesson_description, instrument_type, lesson_type, skill_level, price_set_date) values ('morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat', 'cello', 'individual', 'advanced', '2021-11-18');
insert into individual_lesson (lesson_description, instrument_type, lesson_type, skill_level, price_set_date) values ('in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor', 'piano', 'individual', 'beginner', '2020-08-12');
insert into individual_lesson (lesson_description, instrument_type, lesson_type, skill_level, price_set_date) values ('erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget', 'bass guitar', 'individual', 'intermediate', '2021-01-08');

insert into class_room (class_room_name, floor, room_code) values ('Classroom F', 4, 'YZA567');
insert into class_room (class_room_name, floor, room_code) values ('Classroom B', 6, 'DEF456');
insert into class_room (class_room_name, floor, room_code) values ('Classroom E', 9, 'YZA567');
insert into class_room (class_room_name, floor, room_code) values ('Classroom E', 10, 'DEF456');
insert into class_room (class_room_name, floor, room_code) values ('Classroom H', 4, 'JKL012');
insert into class_room (class_room_name, floor, room_code) values ('Classroom G', 1, 'DEF456');
insert into class_room (class_room_name, floor, room_code) values ('Classroom I', 1, 'STU901');
insert into class_room (class_room_name, floor, room_code) values ('Classroom G', 4, 'YZA567');
insert into class_room (class_room_name, floor, room_code) values ('Classroom E', 8, 'VWX234');
insert into class_room (class_room_name, floor, room_code) values ('Classroom E', 5, 'BCD890');

insert into appointment (individual_lesson_id, time_start, time_end, appointment_date, place) values (1, '9:26', '13:00', '2021-02-13', 'Classroom C');
insert into appointment (individual_lesson_id, time_start, time_end, appointment_date, place) values (2, '11:25', '19:29', '2022-06-18', 'Classroom B');
insert into appointment (individual_lesson_id, time_start, time_end, appointment_date, place) values (3, '10:03', '16:04', '2023-03-24', 'Classroom B');
insert into appointment (individual_lesson_id, time_start, time_end, appointment_date, place) values (4, '10:06', '21:13', '2021-09-19', 'Classroom A');
insert into appointment (individual_lesson_id, time_start, time_end, appointment_date, place) values (5, '11:33', '23:34', '2022-12-04', 'Classroom D');
insert into appointment (individual_lesson_id, time_start, time_end, appointment_date, place) values (6, '10:22', '20:01', '2020-08-13', 'Classroom B');
insert into appointment (individual_lesson_id, time_start, time_end, appointment_date, place) values (7, '10:58', '13:39', '2023-01-21', 'at home');
insert into appointment (individual_lesson_id, time_start, time_end, appointment_date, place) values (8, '8:46', '19:30', '2020-10-15', 'Classroom A');
insert into appointment (individual_lesson_id, time_start, time_end, appointment_date, place) values (9, '11:22', '23:48', '2020-08-29', 'Classroom B');
insert into appointment (individual_lesson_id, time_start, time_end, appointment_date, place) values (10, '8:41', '18:29', '2022-12-08', 'Classroom D');
insert into appointment (individual_lesson_id, time_start, time_end, appointment_date, place) values (11, '9:02', '16:28', '2020-08-20', 'Classroom C');
insert into appointment (individual_lesson_id, time_start, time_end, appointment_date, place) values (12, '9:51', '19:58', '2023-02-19', 'Classroom C');
insert into appointment (individual_lesson_id, time_start, time_end, appointment_date, place) values (13, '11:36', '20:07', '2022-05-29', 'Classroom C');
insert into appointment (individual_lesson_id, time_start, time_end, appointment_date, place) values (14, '11:50', '22:08', '2020-08-22', 'at home');
insert into appointment (individual_lesson_id, time_start, time_end, appointment_date, place) values (15, '9:42', '15:00', '2023-11-03', 'Classroom C');
insert into appointment (individual_lesson_id, time_start, time_end, appointment_date, place) values (16, '9:42', '13:52', '2023-04-01', 'Classroom D');
insert into appointment (individual_lesson_id, time_start, time_end, appointment_date, place) values (17, '8:25', '14:47', '2022-09-06', 'Classroom C');
insert into appointment (individual_lesson_id, time_start, time_end, appointment_date, place) values (18, '10:39', '21:38', '2022-04-26', 'Classroom A');
insert into appointment (individual_lesson_id, time_start, time_end, appointment_date, place) values (19, '10:55', '17:08', '2021-04-20', 'Classroom A');
insert into appointment (individual_lesson_id, time_start, time_end, appointment_date, place) values (20, '9:58', '13:46', '2021-07-15', 'at home');

insert into individual_lesson_taken (individual_lesson_id, student_id) values (1, 6);
insert into individual_lesson_taken (individual_lesson_id, student_id) values (2, 16);
insert into individual_lesson_taken (individual_lesson_id, student_id) values (3, 15);
insert into individual_lesson_taken (individual_lesson_id, student_id) values (4, 3);
insert into individual_lesson_taken (individual_lesson_id, student_id) values (5, 17);
insert into individual_lesson_taken (individual_lesson_id, student_id) values (6, 3);
insert into individual_lesson_taken (individual_lesson_id, student_id) values (7, 18);
insert into individual_lesson_taken (individual_lesson_id, student_id) values (8, 11);
insert into individual_lesson_taken (individual_lesson_id, student_id) values (9, 14);
insert into individual_lesson_taken (individual_lesson_id, student_id) values (10, 18);
insert into individual_lesson_taken (individual_lesson_id, student_id) values (11, 20);
insert into individual_lesson_taken (individual_lesson_id, student_id) values (12, 17);
insert into individual_lesson_taken (individual_lesson_id, student_id) values (13, 12);
insert into individual_lesson_taken (individual_lesson_id, student_id) values (14, 5);
insert into individual_lesson_taken (individual_lesson_id, student_id) values (15, 16);
insert into individual_lesson_taken (individual_lesson_id, student_id) values (16, 10);
insert into individual_lesson_taken (individual_lesson_id, student_id) values (17, 19);
insert into individual_lesson_taken (individual_lesson_id, student_id) values (18, 3);
insert into individual_lesson_taken (individual_lesson_id, student_id) values (19, 14);
insert into individual_lesson_taken (individual_lesson_id, student_id) values (20, 18);

insert into individual_lesson_instructed (individual_lesson_id, instructor_id) values (1, 1);
insert into individual_lesson_instructed (individual_lesson_id, instructor_id) values (2, 4);
insert into individual_lesson_instructed (individual_lesson_id, instructor_id) values (3, 5);
insert into individual_lesson_instructed (individual_lesson_id, instructor_id) values (4, 9);
insert into individual_lesson_instructed (individual_lesson_id, instructor_id) values (5, 1);
insert into individual_lesson_instructed (individual_lesson_id, instructor_id) values (6, 7);
insert into individual_lesson_instructed (individual_lesson_id, instructor_id) values (7, 2);
insert into individual_lesson_instructed (individual_lesson_id, instructor_id) values (8, 2);
insert into individual_lesson_instructed (individual_lesson_id, instructor_id) values (9, 10);
insert into individual_lesson_instructed (individual_lesson_id, instructor_id) values (10, 8);
insert into individual_lesson_instructed (individual_lesson_id, instructor_id) values (11, 5);
insert into individual_lesson_instructed (individual_lesson_id, instructor_id) values (12, 5);
insert into individual_lesson_instructed (individual_lesson_id, instructor_id) values (13, 1);
insert into individual_lesson_instructed (individual_lesson_id, instructor_id) values (14, 4);
insert into individual_lesson_instructed (individual_lesson_id, instructor_id) values (15, 10);
insert into individual_lesson_instructed (individual_lesson_id, instructor_id) values (16, 2);
insert into individual_lesson_instructed (individual_lesson_id, instructor_id) values (17, 7);
insert into individual_lesson_instructed (individual_lesson_id, instructor_id) values (18, 1);
insert into individual_lesson_instructed (individual_lesson_id, instructor_id) values (19, 1);
insert into individual_lesson_instructed (individual_lesson_id, instructor_id) values (20, 1);

insert into group_lesson (lesson_description, min_student_allowed, max_student_allowed, time_start, time_end, lesson_date, instrument_type, class_room_id, lesson_type, skill_level, price_set_date) values ('orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem', 5, 79, '14:26', '12:25', '2023-07-25', 'piano', 10, 'group', 'beginner', '2022-06-25');
insert into group_lesson (lesson_description, min_student_allowed, max_student_allowed, time_start, time_end, lesson_date, instrument_type, class_room_id, lesson_type, skill_level, price_set_date) values ('odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet', 6, 69, '6:50', '12:48', '2023-03-13', 'guitar', 10, 'group', 'beginner', '2022-06-25');
insert into group_lesson (lesson_description, min_student_allowed, max_student_allowed, time_start, time_end, lesson_date, instrument_type, class_room_id, lesson_type, skill_level, price_set_date) values ('ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam', 5, 52, '19:00', '12:40', '2021-12-25', 'bass guitar', 3, 'group', 'beginner', '2021-08-16');
insert into group_lesson (lesson_description, min_student_allowed, max_student_allowed, time_start, time_end, lesson_date, instrument_type, class_room_id, lesson_type, skill_level, price_set_date) values ('justo in hac habitasse platea dictumst etiam faucibus cursus urna ut', 5, 96, '12:02', '12:10', '2022-08-05', 'cello', 9, 'group', 'advanced', '2021-06-23');
insert into group_lesson (lesson_description, min_student_allowed, max_student_allowed, time_start, time_end, lesson_date, instrument_type, class_room_id, lesson_type, skill_level, price_set_date) values ('ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa', 5, 31, '14:42', '12:38', '2022-02-19', 'drums', 3, 'group', 'advanced', '2021-06-23');
insert into group_lesson (lesson_description, min_student_allowed, max_student_allowed, time_start, time_end, lesson_date, instrument_type, class_room_id, lesson_type, skill_level, price_set_date) values ('aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus', 1, 71, '11:45', '12:57', '2021-10-07', 'drums', 6, 'group', 'beginner', '2021-08-16');
insert into group_lesson (lesson_description, min_student_allowed, max_student_allowed, time_start, time_end, lesson_date, instrument_type, class_room_id, lesson_type, skill_level, price_set_date) values ('interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia', 3, 65, '5:02', '12:06', '2022-02-04', 'cello', 4, 'group', 'advanced', '2021-06-23');
insert into group_lesson (lesson_description, min_student_allowed, max_student_allowed, time_start, time_end, lesson_date, instrument_type, class_room_id, lesson_type, skill_level, price_set_date) values ('vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin', 7, 96, '5:37', '12:46', '2022-12-21', 'bass guitar', 7, 'group', 'intermediate', '2021-07-28');
insert into group_lesson (lesson_description, min_student_allowed, max_student_allowed, time_start, time_end, lesson_date, instrument_type, class_room_id, lesson_type, skill_level, price_set_date) values ('risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet', 3, 95, '15:23', '12:01', '2021-09-07', 'piano', 5, 'group', 'beginner', '2021-08-16');
insert into group_lesson (lesson_description, min_student_allowed, max_student_allowed, time_start, time_end, lesson_date, instrument_type, class_room_id, lesson_type, skill_level, price_set_date) values ('vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante', 7, 72, '1:19', '12:12', '2023-09-18', 'saxophone', 4, 'group', 'intermediate', '2023-02-01');

insert into group_lesson_taken (group_lesson_id, student_id) values (2, 13);
insert into group_lesson_taken (group_lesson_id, student_id) values (8, 15);
insert into group_lesson_taken (group_lesson_id, student_id) values (1, 8);
insert into group_lesson_taken (group_lesson_id, student_id) values (5, 20);
insert into group_lesson_taken (group_lesson_id, student_id) values (1, 15);
insert into group_lesson_taken (group_lesson_id, student_id) values (1, 14);
insert into group_lesson_taken (group_lesson_id, student_id) values (8, 18);
insert into group_lesson_taken (group_lesson_id, student_id) values (10, 15);
insert into group_lesson_taken (group_lesson_id, student_id) values (8, 9);
insert into group_lesson_taken (group_lesson_id, student_id) values (8, 14);
insert into group_lesson_taken (group_lesson_id, student_id) values (3, 1);
insert into group_lesson_taken (group_lesson_id, student_id) values (7, 13);
insert into group_lesson_taken (group_lesson_id, student_id) values (9, 1);
insert into group_lesson_taken (group_lesson_id, student_id) values (3, 2);
insert into group_lesson_taken (group_lesson_id, student_id) values (1, 4);
insert into group_lesson_taken (group_lesson_id, student_id) values (3, 14);
insert into group_lesson_taken (group_lesson_id, student_id) values (7, 14);
insert into group_lesson_taken (group_lesson_id, student_id) values (6, 6);
insert into group_lesson_taken (group_lesson_id, student_id) values (3, 11);
insert into group_lesson_taken (group_lesson_id, student_id) values (6, 10);

insert into group_lesson_instructed (group_lesson_id, instructor_id) values (7, 3);
insert into group_lesson_instructed (group_lesson_id, instructor_id) values (9, 1);
insert into group_lesson_instructed (group_lesson_id, instructor_id) values (10, 7);
insert into group_lesson_instructed (group_lesson_id, instructor_id) values (1, 4);
insert into group_lesson_instructed (group_lesson_id, instructor_id) values (7, 5);
insert into group_lesson_instructed (group_lesson_id, instructor_id) values (2, 7);
insert into group_lesson_instructed (group_lesson_id, instructor_id) values (9, 9);
insert into group_lesson_instructed (group_lesson_id, instructor_id) values (10, 6);
insert into group_lesson_instructed (group_lesson_id, instructor_id) values (2, 2);
insert into group_lesson_instructed (group_lesson_id, instructor_id) values (8, 3);
insert into group_lesson_instructed (group_lesson_id, instructor_id) values (6, 6);
insert into group_lesson_instructed (group_lesson_id, instructor_id) values (7, 4);
insert into group_lesson_instructed (group_lesson_id, instructor_id) values (1, 10);
insert into group_lesson_instructed (group_lesson_id, instructor_id) values (6, 9);
insert into group_lesson_instructed (group_lesson_id, instructor_id) values (6, 3);
insert into group_lesson_instructed (group_lesson_id, instructor_id) values (2, 9);
insert into group_lesson_instructed (group_lesson_id, instructor_id) values (4, 1);
insert into group_lesson_instructed (group_lesson_id, instructor_id) values (5, 5);
insert into group_lesson_instructed (group_lesson_id, instructor_id) values (4, 5);

insert into ensamble (lesson_description, min_student_allowed, max_student_allowed, time_start, time_end, lesson_date, genre, class_room_id, lesson_type, skill_level, price_set_date) values ('luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus', 1, 64, '0:00', '12:11', '2022-03-01', 'electronic', 6, 'ensamble', 'advanced', '2020-10-21');
insert into ensamble (lesson_description, min_student_allowed, max_student_allowed, time_start, time_end, lesson_date, genre, class_room_id, lesson_type, skill_level, price_set_date) values ('felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices', 4, 62, '0:00', '12:13', '2022-06-14', 'rock', 7, 'ensamble', 'beginner', '2022-02-11');
insert into ensamble (lesson_description, min_student_allowed, max_student_allowed, time_start, time_end, lesson_date, genre, class_room_id, lesson_type, skill_level, price_set_date) values ('diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien', 5, 27, '0:00', '12:24', '2023-03-09', 'classical', 4, 'ensamble', 'beginner', '2022-07-25');
insert into ensamble (lesson_description, min_student_allowed, max_student_allowed, time_start, time_end, lesson_date, genre, class_room_id, lesson_type, skill_level, price_set_date) values ('vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci', 1, 65, '0:00', '12:02', '2021-09-27', 'hip hop', 3, 'ensamble', 'beginner', '2020-08-13');
insert into ensamble (lesson_description, min_student_allowed, max_student_allowed, time_start, time_end, lesson_date, genre, class_room_id, lesson_type, skill_level, price_set_date) values ('tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat', 5, 61, '0:00', '12:24', '2022-03-24', 'country', 10, 'ensamble', 'beginner', '2022-02-11');
insert into ensamble (lesson_description, min_student_allowed, max_student_allowed, time_start, time_end, lesson_date, genre, class_room_id, lesson_type, skill_level, price_set_date) values ('convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas', 9, 24, '0:00', '12:35', '2021-02-22', 'jazz', 8, 'ensamble', 'advanced', '2020-10-21');
insert into ensamble (lesson_description, min_student_allowed, max_student_allowed, time_start, time_end, lesson_date, genre, class_room_id, lesson_type, skill_level, price_set_date) values ('vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum', 1, 23, '0:00', '12:18', '2021-08-15', 'electronic', 6, 'ensamble', 'beginner', '2020-08-13');
insert into ensamble (lesson_description, min_student_allowed, max_student_allowed, time_start, time_end, lesson_date, genre, class_room_id, lesson_type, skill_level, price_set_date) values ('dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus', 2, 56, '0:00', '12:09', '2021-02-26', 'pop', 5, 'ensamble', 'intermediate', '2022-07-28');
insert into ensamble (lesson_description, min_student_allowed, max_student_allowed, time_start, time_end, lesson_date, genre, class_room_id, lesson_type, skill_level, price_set_date) values ('non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis', 6, 33, '0:00', '12:25', '2022-06-06', 'rock', 9, 'ensamble', 'advanced', '2020-10-21');
insert into ensamble (lesson_description, min_student_allowed, max_student_allowed, time_start, time_end, lesson_date, genre, class_room_id, lesson_type, skill_level, price_set_date) values ('at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt', 8, 44, '0:00', '12:43', '2022-02-05', 'jazz', 4, 'ensamble', 'intermediate', '2022-07-28');

insert into ensamble_instrument_type (instrument_type, ensamble_id) values ('bass guitar', 9);
insert into ensamble_instrument_type (instrument_type, ensamble_id) values ('cello', 2);
insert into ensamble_instrument_type (instrument_type, ensamble_id) values ('cello', 9);
insert into ensamble_instrument_type (instrument_type, ensamble_id) values ('flute', 10);
insert into ensamble_instrument_type (instrument_type, ensamble_id) values ('piano', 2);
insert into ensamble_instrument_type (instrument_type, ensamble_id) values ('drums', 6);
insert into ensamble_instrument_type (instrument_type, ensamble_id) values ('piano', 6);
insert into ensamble_instrument_type (instrument_type, ensamble_id) values ('piano', 3);
insert into ensamble_instrument_type (instrument_type, ensamble_id) values ('bass guitar', 8);
insert into ensamble_instrument_type (instrument_type, ensamble_id) values ('guitar', 5);
insert into ensamble_instrument_type (instrument_type, ensamble_id) values ('drums', 2);
insert into ensamble_instrument_type (instrument_type, ensamble_id) values ('piano', 7);
insert into ensamble_instrument_type (instrument_type, ensamble_id) values ('trumpet', 3);
insert into ensamble_instrument_type (instrument_type, ensamble_id) values ('cello', 3);
insert into ensamble_instrument_type (instrument_type, ensamble_id) values ('ukulele', 10);
insert into ensamble_instrument_type (instrument_type, ensamble_id) values ('saxophone', 8);
insert into ensamble_instrument_type (instrument_type, ensamble_id) values ('violin', 8);
insert into ensamble_instrument_type (instrument_type, ensamble_id) values ('saxophone', 4);
insert into ensamble_instrument_type (instrument_type, ensamble_id) values ('guitar', 8);

insert into ensamble_taken (ensamble_id, student_id) values (9, 20);
insert into ensamble_taken (ensamble_id, student_id) values (10, 14);
insert into ensamble_taken (ensamble_id, student_id) values (10, 15);
insert into ensamble_taken (ensamble_id, student_id) values (6, 1);
insert into ensamble_taken (ensamble_id, student_id) values (9, 14);
insert into ensamble_taken (ensamble_id, student_id) values (7, 6);
insert into ensamble_taken (ensamble_id, student_id) values (8, 20);
insert into ensamble_taken (ensamble_id, student_id) values (8, 3);
insert into ensamble_taken (ensamble_id, student_id) values (8, 8);
insert into ensamble_taken (ensamble_id, student_id) values (3, 18);
insert into ensamble_taken (ensamble_id, student_id) values (9, 15);
insert into ensamble_taken (ensamble_id, student_id) values (10, 2);
insert into ensamble_taken (ensamble_id, student_id) values (2, 16);
insert into ensamble_taken (ensamble_id, student_id) values (7, 5);
insert into ensamble_taken (ensamble_id, student_id) values (4, 4);
insert into ensamble_taken (ensamble_id, student_id) values (5, 17);
insert into ensamble_taken (ensamble_id, student_id) values (2, 18);
insert into ensamble_taken (ensamble_id, student_id) values (4, 16);
insert into ensamble_taken (ensamble_id, student_id) values (9, 4);
insert into ensamble_taken (ensamble_id, student_id) values (9, 5);

insert into ensamble_instructed (ensamble_id, instructor_id) values (5, 6);
insert into ensamble_instructed (ensamble_id, instructor_id) values (3, 6);
insert into ensamble_instructed (ensamble_id, instructor_id) values (2, 5);
insert into ensamble_instructed (ensamble_id, instructor_id) values (2, 3);
insert into ensamble_instructed (ensamble_id, instructor_id) values (7, 7);
insert into ensamble_instructed (ensamble_id, instructor_id) values (10, 9);
insert into ensamble_instructed (ensamble_id, instructor_id) values (9, 4);
insert into ensamble_instructed (ensamble_id, instructor_id) values (8, 7);
insert into ensamble_instructed (ensamble_id, instructor_id) values (3, 7);
insert into ensamble_instructed (ensamble_id, instructor_id) values (3, 3);
insert into ensamble_instructed (ensamble_id, instructor_id) values (5, 1);
insert into ensamble_instructed (ensamble_id, instructor_id) values (10, 6);
insert into ensamble_instructed (ensamble_id, instructor_id) values (1, 7);
insert into ensamble_instructed (ensamble_id, instructor_id) values (1, 4);
insert into ensamble_instructed (ensamble_id, instructor_id) values (7, 4);
insert into ensamble_instructed (ensamble_id, instructor_id) values (1, 2);
insert into ensamble_instructed (ensamble_id, instructor_id) values (1, 1);
insert into ensamble_instructed (ensamble_id, instructor_id) values (6, 4);
insert into ensamble_instructed (ensamble_id, instructor_id) values (5, 3);
